import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox4widget/generated/GeneratedStatusbarWidget1.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox4widget/generated/GeneratedTapsafew1Widget1.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox4widget/generated/GeneratedButtonsWidget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox4widget/generated/GeneratedBgWidget2.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox4widget/generated/GeneratedCloseWidget2.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox4widget/generated/GeneratedTasksbarWidget1.dart';

/* Frame iPhone 11 Pro / X - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -0.0003662109375,
                top: 0.0003662109375,
                right: null,
                bottom: null,
                width: 375.00042724609375,
                height: 811.9991455078125,
                child: GeneratedBgWidget2(),
              ),
              Positioned(
                left: 71.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 99.0,
                child: GeneratedButtonsWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 794.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 8.0,
                child: GeneratedTasksbarWidget1(),
              ),
              Positioned(
                left: 27.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 13.992074966430664,
                height: 13.992011070251465,
                child: GeneratedCloseWidget2(),
              ),
              Positioned(
                left: 34.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 326.3334655761719,
                height: 15.0,
                child: GeneratedStatusbarWidget1(),
              ),
              Positioned(
                left: 77.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 293.0,
                child: GeneratedTapsafew1Widget1(),
              )
            ]),
      ),
    ));
  }
}
