import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedProtectionWidget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedProtect1Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedCloseWidget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox2widget/generated/GeneratedMakesureyouarealwaysinsafestsurrondingbycheckingforsafe.dart';

/* Frame iPhone 11 Pro / X - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProX3Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedRectangle1Widget(),
                ),
                Positioned(
                  left: 38.0,
                  top: 559.0,
                  right: null,
                  bottom: null,
                  width: 301.0,
                  height: 137.0,
                  child:
                      GeneratedMakesureyouarealwaysinsafestsurrondingbycheckingforsafe(),
                ),
                Positioned(
                  left: 86.0,
                  top: 475.0,
                  right: null,
                  bottom: null,
                  width: 207.0,
                  height: 43.0,
                  child: GeneratedProtectionWidget(),
                ),
                Positioned(
                  left: 161.0,
                  top: 778.0,
                  right: null,
                  bottom: null,
                  width: 8.0,
                  height: 10.0,
                  child: GeneratedEllipse1Widget(),
                ),
                Positioned(
                  left: 184.0,
                  top: 778.0,
                  right: null,
                  bottom: null,
                  width: 9.0,
                  height: 10.0,
                  child: GeneratedEllipse2Widget(),
                ),
                Positioned(
                  left: 207.0,
                  top: 778.0,
                  right: null,
                  bottom: null,
                  width: 8.0,
                  height: 10.0,
                  child: GeneratedEllipse3Widget(),
                ),
                Positioned(
                  left: 26.0,
                  top: 71.0,
                  right: null,
                  bottom: null,
                  width: 323.0,
                  height: 355.0,
                  child: GeneratedProtect1Widget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 45.0,
                  right: null,
                  bottom: null,
                  width: 13.992074966430664,
                  height: 13.992011070251465,
                  child: GeneratedCloseWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
