import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/Generated3Widget13.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/Generated4Widget7.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedDividersWidget6.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/Generated2Widget13.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedObjectWidget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/Generated6Widget1.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedBtnWidget89.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedOnlinedotsWidget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedBaseWidget162.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedMenubarWidget10.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedSettingsWidget13.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedIPhone11ProX25Widget1.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedIconWidget101.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/Generated1Widget13.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox24widget/generated/GeneratedLowvolume1Widget.dart';

/* Frame iPhone 11 Pro / X - 24
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX24Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedIPhone11ProX25Widget1(),
              ),
              Positioned(
                left: 0.00018095970153808594,
                top: 142.00010681152344,
                right: null,
                bottom: null,
                width: 375.0,
                height: 672.1765747070312,
                child: GeneratedBaseWidget162(),
              ),
              Positioned(
                left: 34.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 30.0,
                child: GeneratedSettingsWidget13(),
              ),
              Positioned(
                left: 27.0,
                top: 222.057861328125,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated1Widget13(),
              ),
              Positioned(
                left: 27.0,
                top: 313.971923828125,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated2Widget13(),
              ),
              Positioned(
                left: 27.0,
                top: 405.8857421875,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated3Widget13(),
              ),
              Positioned(
                left: 27.0,
                top: 497.79931640625,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated4Widget7(),
              ),
              Positioned(
                left: 27.0,
                top: 681.626953125,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated6Widget1(),
              ),
              Positioned(
                left: -117.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 463.43939208984375,
                child: GeneratedDividersWidget6(),
              ),
              Positioned(
                left: 73.0,
                top: 266.563720703125,
                right: null,
                bottom: null,
                width: 13.0,
                height: 288.3191223144531,
                child: GeneratedOnlinedotsWidget(),
              ),
              Positioned(
                left: -80.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 519.0,
                height: 282.00006103515625,
                child: GeneratedObjectWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 335.00048828125,
                height: 97.99993896484375,
                child: GeneratedMenubarWidget10(),
              ),
              Positioned(
                left: 332.0628662109375,
                top: 33.77437210083008,
                right: null,
                bottom: null,
                width: 18.5422420501709,
                height: 17.225627899169922,
                child: GeneratedIconWidget101(),
              ),
              Positioned(
                left: 22.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 59.18386459350586,
                height: 49.934627532958984,
                child: GeneratedBtnWidget89(),
              ),
              Positioned(
                left: 39.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedLowvolume1Widget(),
              )
            ]),
      ),
    ));
  }
}
