import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedTargetWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedGroupWidget9.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedItemsWidget4.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedTopbarWidget28.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedMapsWidget4.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedSearchWidget4.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedStatusbarWidget19.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox39widget/generated/GeneratedGroup8Widget1.dart';

/* Frame iPhone 11 Pro / X - 39
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX39Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0426666666666666;

                  final double height =
                      constraints.maxHeight * 1.0369458128078817;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMapsWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 8.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMenuWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.2933333333333332;

                  final double height =
                      constraints.maxHeight * 0.25985221674876846;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.6970443349753694,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedItemsWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 34.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 326.33343505859375,
                height: 20.0,
                child: GeneratedStatusbarWidget19(),
              ),
              Positioned(
                left: 61.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 117.0,
                child: GeneratedSearchWidget4(),
              ),
              Positioned(
                left: 8.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedTargetWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.48;

                  final double height =
                      constraints.maxHeight * 0.32019704433497537;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24533333333333332,
                        y: constraints.maxHeight * 0.29433497536945813,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 126.0,
                child: GeneratedTopbarWidget28(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05333333333333334;

                  final double height =
                      constraints.maxHeight * 0.10099724830665024;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.208,
                        y: constraints.maxHeight * 0.16009852216748768,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup8Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 374.99981689453125,
                height: 496.0,
                child: GeneratedGroup9Widget(),
              )
            ]),
      ),
    ));
  }
}
