import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox22widget/generated/GeneratedCloseWidget7.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox22widget/generated/GeneratedFormWidget6.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox22widget/generated/GeneratedBgWidget32.dart';

/* Frame iPhone 11 Pro / X - 22
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX22Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.909832000732422,
                top: 46.85487747192383,
                right: null,
                bottom: null,
                width: 49.73473358154297,
                height: 49.944217681884766,
                child: GeneratedCloseWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBgWidget32(),
              ),
              Positioned(
                left: 0.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 374.9997863769531,
                height: 703.2146606445312,
                child: GeneratedFormWidget6(),
              )
            ]),
      ),
    ));
  }
}
