import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox5widget/generated/GeneratedBgWidget4.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox5widget/generated/GeneratedTasksbarWidget2.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox5widget/generated/GeneratedStatusbarWidget2.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox5widget/generated/GeneratedTapsafew1Widget2.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox5widget/generated/GeneratedAgeWidget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox5widget/generated/GeneratedCloseWidget3.dart';

/* Frame iPhone 11 Pro / X - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -0.0003662109375,
                top: 0.0003662109375,
                right: null,
                bottom: null,
                width: 375.00042724609375,
                height: 811.9991455078125,
                child: GeneratedBgWidget4(),
              ),
              Positioned(
                left: 40.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 56.0,
                child: GeneratedAgeWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 794.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 8.0,
                child: GeneratedTasksbarWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 13.992074966430664,
                height: 13.992011070251465,
                child: GeneratedCloseWidget3(),
              ),
              Positioned(
                left: 34.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 326.3334655761719,
                height: 15.0,
                child: GeneratedStatusbarWidget2(),
              ),
              Positioned(
                left: 77.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 293.0,
                child: GeneratedTapsafew1Widget2(),
              )
            ]),
      ),
    ));
  }
}
