import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedObjectWidget1.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedDividersWidget7.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/Generated6Widget3.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/Generated2Widget15.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/Generated3Widget15.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedIconWidget103.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedIPhone11ProX25Widget2.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedMenubarWidget11.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/Generated1Widget15.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedOnlinedotsWidget1.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/Generated5Widget2.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedBaseWidget164.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedBtnWidget92.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedSettingsWidget15.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/Generated4Widget9.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox35widget/generated/GeneratedLowvolume1Widget1.dart';

/* Frame iPhone 11 Pro / X - 35
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX35Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedIPhone11ProX25Widget2(),
              ),
              Positioned(
                left: 0.00018095970153808594,
                top: 142.00010681152344,
                right: null,
                bottom: null,
                width: 375.0,
                height: 672.1765747070312,
                child: GeneratedBaseWidget164(),
              ),
              Positioned(
                left: 34.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 30.0,
                child: GeneratedSettingsWidget15(),
              ),
              Positioned(
                left: 27.0,
                top: 222.057861328125,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated1Widget15(),
              ),
              Positioned(
                left: 27.0,
                top: 313.971923828125,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated2Widget15(),
              ),
              Positioned(
                left: 27.0,
                top: 405.8857421875,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated3Widget15(),
              ),
              Positioned(
                left: 27.0,
                top: 497.79931640625,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated4Widget9(),
              ),
              Positioned(
                left: 27.0,
                top: 589.71337890625,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated5Widget2(),
              ),
              Positioned(
                left: 27.0,
                top: 681.626953125,
                right: null,
                bottom: null,
                width: 317.0,
                height: 59.98585510253906,
                child: Generated6Widget3(),
              ),
              Positioned(
                left: -117.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 463.43939208984375,
                child: GeneratedDividersWidget7(),
              ),
              Positioned(
                left: 73.0,
                top: 266.563720703125,
                right: null,
                bottom: null,
                width: 13.0,
                height: 380.2329406738281,
                child: GeneratedOnlinedotsWidget1(),
              ),
              Positioned(
                left: -80.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 519.0,
                height: 282.00006103515625,
                child: GeneratedObjectWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 335.00048828125,
                height: 97.99993896484375,
                child: GeneratedMenubarWidget11(),
              ),
              Positioned(
                left: 332.0628662109375,
                top: 33.77437210083008,
                right: null,
                bottom: null,
                width: 18.5422420501709,
                height: 17.225627899169922,
                child: GeneratedIconWidget103(),
              ),
              Positioned(
                left: 22.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 59.18386459350586,
                height: 49.934627532958984,
                child: GeneratedBtnWidget92(),
              ),
              Positioned(
                left: 39.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedLowvolume1Widget1(),
              )
            ]),
      ),
    ));
  }
}
