import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox30widget/generated/GeneratedIconWidget104.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox30widget/generated/GeneratedTopbarWidget34.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox30widget/generated/GeneratedFormWidget8.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox30widget/generated/GeneratedBaseWidget166.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox30widget/generated/GeneratedTasksbarWidget29.dart';

/* Frame iPhone 11 Pro / X - 30
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX30Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -11.0,
                top: -22.0,
                right: null,
                bottom: null,
                width: 398.99981689453125,
                height: 834.1765747070312,
                child: GeneratedBaseWidget166(),
              ),
              Positioned(
                left: 118.000244140625,
                top: 795.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 8.0,
                child: GeneratedTasksbarWidget29(),
              ),
              Positioned(
                left: 0.0,
                top: 153.99928283691406,
                right: null,
                bottom: null,
                width: 375.00018310546875,
                height: 443.0006408691406,
                child: GeneratedFormWidget8(),
              ),
              Positioned(
                left: 171.7078399658203,
                top: 178.2256317138672,
                right: null,
                bottom: null,
                width: 33.12654113769531,
                height: 30.77437400817871,
                child: GeneratedIconWidget104(),
              ),
              Positioned(
                left: 29.999755859375,
                top: 63.007869720458984,
                right: null,
                bottom: null,
                width: 308.000244140625,
                height: 22.9921875,
                child: GeneratedTopbarWidget34(),
              )
            ]),
      ),
    ));
  }
}
