import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox23widget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox23widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox23widget/generated/GeneratedSwitcheronWidget10.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox23widget/generated/GeneratedCloseWidget9.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox23widget/generated/GeneratedBgWidget33.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox23widget/generated/GeneratedTasksbarWidget26.dart';

/* Frame iPhone 11 Pro / X - 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.909799575805664,
                top: 46.8548698425293,
                right: null,
                bottom: null,
                width: 49.734737396240234,
                height: 49.944217681884766,
                child: GeneratedCloseWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: -960.5,
                right: null,
                bottom: null,
                width: 1433.5,
                height: 1772.5001220703125,
                child: GeneratedBgWidget33(),
              ),
              Positioned(
                left: 0.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 374.9997863769531,
                height: 704.21337890625,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 304.34783935546875,
                top: 210.25001525878906,
                right: null,
                bottom: null,
                width: 42.771873474121094,
                height: 27.968761444091797,
                child: GeneratedSwitcheronWidget10(),
              ),
              Positioned(
                left: 200.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 90.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 138.99984741210938,
                height: 7.991074562072754,
                child: GeneratedTasksbarWidget26(),
              )
            ]),
      ),
    ));
  }
}
