import 'package:flutter/material.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedOnclickingAlertButtonYourphonewillstartrecordingautomat.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedCloseWidget1.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedRecordingWidget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedRecording1Widget.dart';
import 'package:flutterapp/tapsafeapp/generatediphone11prox3widget/generated/GeneratedEllipse5Widget.dart';

/* Frame iPhone 11 Pro / X - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProX4Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedRectangle2Widget(),
                ),
                Positioned(
                  left: 33.0,
                  top: 556.0,
                  right: null,
                  bottom: null,
                  width: 311.0,
                  height: 179.0,
                  child:
                      GeneratedOnclickingAlertButtonYourphonewillstartrecordingautomat(),
                ),
                Positioned(
                  left: 84.0,
                  top: 477.0,
                  right: null,
                  bottom: null,
                  width: 212.0,
                  height: 39.0,
                  child: GeneratedRecordingWidget(),
                ),
                Positioned(
                  left: 161.0,
                  top: 778.0,
                  right: null,
                  bottom: null,
                  width: 8.0,
                  height: 10.0,
                  child: GeneratedEllipse4Widget(),
                ),
                Positioned(
                  left: 184.0,
                  top: 778.0,
                  right: null,
                  bottom: null,
                  width: 9.0,
                  height: 10.0,
                  child: GeneratedEllipse5Widget(),
                ),
                Positioned(
                  left: 207.0,
                  top: 778.0,
                  right: null,
                  bottom: null,
                  width: 8.0,
                  height: 10.0,
                  child: GeneratedEllipse6Widget(),
                ),
                Positioned(
                  left: 29.0,
                  top: 67.0,
                  right: null,
                  bottom: null,
                  width: 318.0,
                  height: 361.0,
                  child: GeneratedRecording1Widget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 45.0,
                  right: null,
                  bottom: null,
                  width: 13.992074966430664,
                  height: 13.992011070251465,
                  child: GeneratedCloseWidget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
